version: '3'
services:
  tic-tac-toe-server:
    image: node:16-alpine
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - JWT_SECRET_KEY=todolistserv
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=tododb
      - DB_USER=testuser
      - DB_PASSWORD=testcreds
      - CLIENT_ORIGIN=http://localhost:8000

  db:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testcreds
      - POSTGRES_DB=tododb

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
